# Generated by Django 5.2.1 on 2025-05-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='NI',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
