# Generated by Django 5.2.1 on 2025-05-09 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_alter_reservaambiente_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ser no formarto (xx)xxxxx-xxxx', regex='^\\(\\d{2}\\)\\d{5}[-]\\d{4}$')]),
        ),
    ]
