# Generated by Django 5.1.7 on 2025-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_alter_reservaambiente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaambiente',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservaambiente',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
